### PR TITLE
Add Countries & Currencies

### PR DESCRIPTION
**Pull request by mikeclimbrock**
Support countries/currencies for `Angola`, `Madagascar`, `Mozambique`, `Suriname`, `Tajikistan`, `Turkmenistan`

Confirmed OpenExchangeRates provides rates:
https://docs.openexchangerates.org/docs/supported-currencies

Confirmed Adyen does *not* support `MGA`, `TMT`, `TJS`, `SRD`:
https://docs.adyen.com/developers/currency-codes

### CODE REVIEW

**Comment by ericluria** [comment]
What are we going to do about the unsupported currency codes? I don't think it's safe to deploy this change until we add some logic to payment to convert to a supported currency.

**Comment by mikeclimbrock** [comment]
@ericluria do we have any existing process for this in `payment` today, for which we convert an unsupported Adyen currency?

**Comment by ericluria** [comment]
@mikeclimbrock I think we _might_ do this for PayPal, but I would need to look. I'm 99% certain that we do not do this for Adyen transactions.

**Comment by mikeclimbrock** [comment]
In fact, we'd need to potentially convert for _all_ payment types, not just Adyen.  For example, PayPal might support some of the ones Adyen doesn't but not support others.

**Comment by mbryzek** [comment]
> What are we going to do about the unsupported currency codes?

Payment needs to have a list of supported currencies by processor (like we do for paypal) and to internally convert end user currency request to one of the supported ones.

@andrewfchen  @ericluria can you scope this as this is the right solution.

In interim - let's update `json-reference` to use `EUR` as the currencies in place of MGA, TMT, TJS, SRD until we support [hack for now].

**Comment by andrewfchen** [comment]
yes, i'll work with @ericluria on this

**Pull request merged**
