### PR TITLE
add Myanmar

### PR DESCRIPTION
**Pull request by aksharp**

### CODE REVIEW

**Comment by paololim** [comment]
See: https://github.com/flowcommerce/json-reference/blob/master/common/common.go#L344

I think removing that one single line and then running the generator scripts should work.

**Comment by mikeclimbrock** [comment]
is it blacklisted for a particular reason perhaps?

**Comment by paololim** [comment]
I don't know. Technically, I think it probably is better not to blacklist, but just the fact there are no ratecards to myanmar means that you cant ship there. The country exists, so may just be a good idea to actually acknowledge it exists

**Comment by aksharp** [comment]
as per @ericluria suggestion closing this PR for now

**Pull request closed without merging**
