### PR TITLE
update currency for Croatia

### PR DESCRIPTION
**Pull request by prakhar-flow**
[JIRA](https://flowio.atlassian.net/browse/COR-4)

This PR aims to:
- Change the default currency for Croatia to EUR
- Add Croatia to Eurozone

Related PRs
- https://github.com/flowcommerce/lib-reference-javascript/pull/39
- https://github.com/flowcommerce/lib-reference-scala/pull/165
- https://github.com/flowcommerce/lib-reference-ruby/pull/20

### CODE REVIEW

**Review by jconnolly — APPROVED** [review]
lgtm

**Review by mikeclimbrock — COMMENTED** [review]
add `HRV` to `europeanregion` region

**Comment by prakhar-flow** [comment]
> add `HRV` to `europeanregion` region

@mikeclimbrock HRV is added to thr EU region
https://github.com/flowcommerce/json-reference/pull/118/files#diff-7d326cc4997347ce4b40b4f73e6711b399cbb925e437e4464604574d340177ebL1788

**Comment by prakhar-flow** [comment]
Follow up [PR](https://github.com/flowcommerce/json-reference/pull/119)

**Pull request merged**
