### PR TITLE
Euro Regions (Union, Economic Area)

### PR DESCRIPTION
**Pull request by dasmb**

### CODE REVIEW

**Comment by paololim** [comment]
That's different than eurozone?

**Comment by paololim** [comment]
lgtm otherwise

**Comment by dasmb** [comment]
https://upload.wikimedia.org/wikipedia/commons/1/1a/Supranational_European_Bodies-en.svg

**Comment by dasmb** [comment]
Eurozone: 19+ countries, share common currency (some having adopted it without permission of the EU)
EU: 28 countries, share common governance
EEA: 31 countries, share common right of movement / trade

The Flow region called "Eurozone" has 30 countries in it, as it includes all countries that use the Euro regardless of whether they are members of the EU (Andorra, Saint Barthélemy, Guadeloupe, French Guiana, Saint Martin, Monaco, Montenegro, Martinique, Mayotte,  Reunion and San Marino). This is probably a desirable definition when grouping countries that have common currency rules, but it's possibly less desirable when grouping countries with common legal frameworks (such as GDPR)

**Pull request merged**
