### PR TITLE
Updated Unsupported Countries

### PR DESCRIPTION
**Pull request by andrewfchen**
Updated ISO code for Antarctica also added North Korea

### CODE REVIEW

**Comment by paololim** [comment]
What is the actual intent of this change?

**Comment by andrewfchen** [comment]
to add 1) north korea as unsupported (can't ship to or appear) and 2) to fix antarctica's iso code and thus, ensure it's unsupported

**Comment by paololim** [comment]
North Korea is an actual country that exists though. I think reference data should reflect this fact. If the issue is that we want to prevent the country from showing up in the drop down, I propose the change I already mentioned here: https://app.clubhouse.io/flow/story/15557/why-do-north-korea-and-afghanistan-show-up-as-countries-in-the-gymboree-country-picker#activity-15850

**Comment by andrewfchen** [comment]
Got it... but what does this code do - it already exists:

func UnsupportedCountryCodes() []string {
	return []string{
		"AF",
		"AQ",
		"ER",
		"KP",
		"IQ",
		"PS",
		"SD",
		"SS",
		"SR",
		"SY",
		"TJ",

**Comment by mbryzek** [comment]
> Got it... but what does this code do - it already exists:
> 
> func UnsupportedCountryCodes() []string {
> return []string{
> "AF",
> "AQ",
> "ER",
> "KP",
> "IQ",
> "PS",
> "SD",
> "SS",
> "SR",
> "SY",
> "TJ",

we need to eventually remove all of these and treat as paolo suggested (the list was longer, but after client reports we've shortened over time)

**Comment by jlogeart** [comment]
Closing as stale

**Pull request closed without merging**
